name: resnet50_cefas_model
url: https://github.com/Tonks684/plankton-cefas-scivision/
import: resnet50_cefas
model: resnet50
args:
    label_level: label3_detritus
prediction_fn:
    call: predict_batch
    args:
        X: image
    kwargs:
        batch_size: 3
